import "/styles/globals.scss";

import type { Metadata } from "next";

import styles from "./layout.module.scss";
import Accounts from "components/layouts/accounts";
import Slides from "components/layouts/slide-text";
import { ReactChildren } from "interfaces/components/shared.interface";
import Footer from "components/layouts/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ReactChildren) {
  return (
    <>
      <main className={styles.layout}>
        <Slides layout="accounts" />
        <Accounts>{children}</Accounts>
      </main>

      <Footer />
    </>
  );
}
